export enum RuleId {
  SetupDraft = 1,
  SetupBuild = 2,
  PlayCard = 3,
  PlayEmptiness = 4,
  PlayVillager = 5,
  PlayJester = 6,
  PlayAssassin = 7,
  PlayMerchant = 8,
  PlayKnight = 9,
  PlayAstrologer = 10,
  MarketBuy = 11,
  AddCardInMarket = 12,
  CitiesConstruction = 13,
  PurpleMajority = 14,
}
